name: Create Archive
on:
  push:
    tags:
      - '1.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure the new version $GITHUB_REF  
        run: |
          sed -i 's/1.0.0/$GITHUB_REF/g' woocommerce-cliqueretire.php
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'woocommerce-cliqueretire.zip'
          exclusions: '*.git* /*docker-compose/* /*circleci*'
