name: Create Archive
on:
  push:
    tags:
      - '1.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Populate values
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Configure the new version
        run: |
          sed -i 's/1.0.0/$SOURCE_TAG/g' woocommerce-cliqueretire.php
        env:
          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'woocommerce-cliqueretire.zip'
          exclusions: '*.git* /*docker-compose/* /*circleci*'
